### ISSUE TITLE
board_database does not appear to identify all boards in the repo.

### ISSUE THREAD

**Issue by Josverl** [mattytrentini/mpbuild#56]
For mpflash I am looking for a way to get the variants , when I realized that you already have the code written 
As I need the full board description in order to identify the board I tried to match the results of my [parsing of .cmake and .h files](https://github.com/Josverl/micropython-stubber/blob/mpflash/mp_version_patch/src/mpflash/mpflash/mpboard_id/add_boards.py) with the results of db.ports from [board_database.py](https://github.com/mattytrentini/mpbuild/blob/main/src/mpbuild/board_database.py)

I noted that there appear to be a few boards missing from the database or underlying json data, that are in the make or .h  files.

```
LAUNCHXL, not in db, ports\cc3200\boards\LAUNCHXL\mpconfigboard.h
PYBV3, not in db, ports\stm32\boards\PYBV3\mpconfigboard.h
PYBV4, not in db, ports\stm32\boards\PYBV4\mpconfigboard.h
STM32H573I_DK, not in db, ports\stm32\boards\STM32H573I_DK\mpconfigboard.h
```
I think these boards are each missing a `board.json`
not sure how relevant this is , and the fixing is probably over in the micropython repo, but thought to check in here first.

**Comment by mattytrentini** [comment]
Oh, right, interesting! Yes, mpbuild searches for `build.json` files to populate the board database. I think this should be raised as an issue at MicroPython because, without a `board.json`, firmware files will not be built (you'll notice none of those boards have [pre-built firmware](https://micropython.org/download/)).

Good observation! 

Something we could do is check for this situation though...

**Comment by Josverl** [comment]
Yes thought as much, 
ill raise it on the MP repo
